"use client";

import { verdictFor } from "./types";

/**
 * Readiness report → a clean one-page(ish) PDF. Deliberately a light,
 * printable document — the artefact a champion attaches to an email or
 * an audit trail, not a screenshot of the dark UI.
 */

interface PdfRisk {
  title: string;
  severity?: string;
  body: string;
}

export interface ReportPdfData {
  agentName: string;
  runId: string;
  suiteLine: string;
  dateLine: string;
  score: number;
  metaLine: string;
  strengths: string[];
  weaknesses: string[];
  risks: PdfRisk[];
}

const INK = "#111318";
const SUB = "#555b66";
const ACCENT = "#1f9d5d";
const FAIL = "#c2372f";

export async function generateReportPdf(data: ReportPdfData): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 56;
  let y = 64;

  const text = (
    s: string,
    size: number,
    opts: { color?: string; bold?: boolean; x?: number; maxW?: number; lineGap?: number } = {},
  ) => {
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(opts.color ?? INK);
    const lines = doc.splitTextToSize(s, opts.maxW ?? W - M * 2);
    doc.text(lines, opts.x ?? M, y);
    y += lines.length * size * (opts.lineGap ?? 1.35);
  };
  const ensureRoom = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 56) {
      doc.addPage();
      y = 64;
    }
  };

  text("PREFLIGHT · READINESS REPORT", 8, { color: SUB });
  y += 6;
  text(data.agentName, 24, { bold: true });
  text(`${data.runId} · ${data.suiteLine} · ${data.dateLine}`, 9, { color: SUB });
  y += 14;

  // Score block
  doc.setFont("helvetica", "bold");
  doc.setFontSize(44);
  doc.setTextColor(data.score >= 90 ? ACCENT : data.score >= 75 ? INK : FAIL);
  doc.text(`${data.score}%`, M, y + 20);
  doc.setFontSize(13);
  doc.setTextColor(INK);
  doc.text(verdictFor(data.score), M + 110, y + 6);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(SUB);
  doc.text(doc.splitTextToSize(data.metaLine, W - M * 2 - 110), M + 110, y + 20);
  y += 56;

  doc.setDrawColor(220);
  doc.line(M, y, W - M, y);
  y += 24;

  // Strengths / weaknesses, two columns.
  const colW = (W - M * 2 - 24) / 2;
  const startY = y;
  text("STRENGTHS", 8, { color: SUB, maxW: colW });
  for (const s of data.strengths.slice(0, 6)) {
    doc.setFontSize(10);
    doc.setTextColor(ACCENT);
    doc.text("+", M, y);
    doc.setTextColor(INK);
    doc.text(doc.splitTextToSize(s, colW - 14), M + 12, y);
    y += 15;
  }
  const leftEnd = y;
  y = startY;
  text("WEAKNESSES", 8, { color: SUB, x: M + colW + 24, maxW: colW });
  for (const wk of data.weaknesses.slice(0, 6)) {
    doc.setFontSize(10);
    doc.setTextColor(FAIL);
    doc.text("×", M + colW + 24, y);
    doc.setTextColor(INK);
    doc.text(doc.splitTextToSize(wk, colW - 14), M + colW + 36, y);
    y += 15;
  }
  y = Math.max(leftEnd, y) + 16;

  if (data.risks.length > 0) {
    ensureRoom(60);
    doc.setDrawColor(220);
    doc.line(M, y, W - M, y);
    y += 24;
    text(`THE ${data.risks.length} RISKS THAT MATTER`, 8, { color: SUB });
    y += 4;
    data.risks.forEach((risk, i) => {
      ensureRoom(52);
      text(
        `${i + 1}. ${risk.title}${risk.severity ? `  ·  ${risk.severity.toUpperCase()}` : ""}`,
        11,
        { bold: true },
      );
      text(risk.body, 9.5, { color: SUB });
      y += 8;
    });
  }

  ensureRoom(40);
  y = doc.internal.pageSize.getHeight() - 40;
  doc.setFontSize(8);
  doc.setTextColor(SUB);
  doc.text(`Generated by Preflight · ${new Date().toISOString().slice(0, 10)}`, M, y);

  doc.save(`preflight-${data.runId}.pdf`);
}
