"use client";

import Link from "next/link";
import { ReadinessCard } from "@/components/readiness-card";
import { Button, Eyebrow } from "@/components/ui";
import { LiveReport } from "@/components/live-report";
import { demoReport } from "@/lib/fixtures/report";
import { readiness, runStats } from "@/lib/fixtures/run";
import { failingReplayId } from "@/lib/fixtures/scenarios";
import { useMode } from "@/lib/mode";

const weaknessHrefs = Object.fromEntries(
  readiness.weaknesses.map((w) => {
    const id = failingReplayId(w);
    return [w, id && `/replay/${id}`];
  }),
);

/**
 * The readiness report — a document, not a dashboard. This is the
 * artefact a champion forwards to their boss.
 */
export default function ReportsPage() {
  const { mode } = useMode();
  if (mode === "live") return <LiveReport />;

  const r = demoReport;

  return (
    <div className="mx-auto max-w-3xl px-8 py-16">
      {/* Document head */}
      <div className="flex items-start justify-between">
        <div>
          <Eyebrow>Readiness report · {r.runId}</Eyebrow>
          <h1 className="font-display mt-3 text-4xl tracking-tight text-ink">
            {r.agent} {r.agentVersion}
          </h1>
          <p className="mt-2 text-sm text-sub">
            {r.suite} · {r.date}
          </p>
        </div>
        <Button
          variant="secondary"
          size="sm"
          className="no-print"
          onClick={() => window.print()}
        >
          Print / share
        </Button>
      </div>

      <div className="mt-10">
        <ReadinessCard
          score={readiness.score}
          strengths={readiness.strengths}
          weaknesses={readiness.weaknesses}
          meta={`Run ${r.runId} · ${runStats.total} scenarios · ${runStats.pass} passed · ${runStats.fail} failed · ${runStats.partial} partial`}
          hrefs={weaknessHrefs}
        />
      </div>

      {/* Failure taxonomy */}
      <section className="mt-16">
        <h2 className="font-display text-2xl tracking-tight text-ink">
          Where it breaks
        </h2>
        <div className="mt-6 space-y-8">
          {r.taxonomy.map((t) => (
            <div key={t.finding} className="border-l-2 border-edge pl-6">
              <div className="flex items-baseline justify-between gap-4">
                <h3 className="text-[15px] font-medium text-ink">{t.finding}</h3>
                <span className="shrink-0 font-mono text-[12px] tabular-nums text-mut">
                  {t.failed} / {t.total}
                </span>
              </div>
              <p className="mt-2 text-sm leading-relaxed text-sub">{t.detail}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Top risks */}
      <section className="mt-16">
        <h2 className="font-display text-2xl tracking-tight text-ink">
          The five risks that matter
        </h2>
        <ol className="mt-6 space-y-6">
          {r.risks.map((risk, i) => (
            <li key={risk.title} className="flex gap-5">
              <span className="numeral mt-0.5 text-2xl text-mut">{i + 1}</span>
              <div>
                <h3 className="text-[15px] font-medium text-ink">{risk.title}</h3>
                <p className="mt-1.5 text-sm leading-relaxed text-sub">
                  {risk.body}
                </p>
                <Link
                  href={`/replay/${risk.replayId}`}
                  className="focus-ring no-print mt-2 inline-block rounded text-[13px] text-accent hover:underline"
                >
                  Watch the replay →
                </Link>
              </div>
            </li>
          ))}
        </ol>
      </section>

      {/* Sign-off */}
      <section className="mt-20 border-t border-edge pt-6">
        <div className="flex flex-wrap items-baseline justify-between gap-4 font-mono text-[12px] text-mut">
          <span>
            {r.agent} {r.agentVersion} · suite {r.suiteVersion}
          </span>
          <span>
            score{" "}
            <span className="text-ink">
              {r.score}%
            </span>{" "}
            · {r.date} · generated by Preflight
          </span>
        </div>
      </section>
    </div>
  );
}
